### PR TITLE
Create make target to push operator to the quay app registry for tests.

### PR DESCRIPTION
**Pull request by pmacik**
This PR:
* Adds a make target (`push-operator-app-registry`) to push freshly built operator to the application registry in quay.io which can be used by `OperatorSource`
* Includes the `tmp` directory created by the above target in the `clean` target
* Adds a make target (`get-operator-version`) that detects the operator version from `./manifests/devconsole/devconsole.package.yaml` file and sets the `DEVCONSOLE_OPERATOR_VERSION` variable.

### CODE REVIEW

**Comment by pmacik** [comment]
> The changes look find - but make push-operator-app-registry results in a docker image being created for the operator.

@ldimaggi Yes, that is because the `push-operator-image` target is called before (as a dependency). The idea is to build fresh local operator image, tag it with the generated unique name - including the `$(TAG)` string - push it to the quay.io image repository and then reference this unique image in the operator manifest that is then used to package the operator application and push it to the app registry with that unique name. Then, the unique operator application can be referenced in the `OperatorSource`.

This approach makes it possible to test the current state of the code of the operator and to test it locally or automated in a "per-PR" manner.

**Comment by ldimaggi** [comment]
The "REPLACE_IMAGE" placeholder here must also be updated before the operator is pushed to quay.io:

https://github.com/redhat-developer/devconsole-operator/blob/master/manifests/devconsole/0.1.0/devconsole-operator.v0.1.0.clusterserviceversion.yaml#L82

**Comment by pmacik** [comment]
> The "REPLACE_IMAGE" placeholder here must also be updated before the operator is pushed to quay.io:

@ldimaggi It is updated - the placeholder is already being replaced. That is what [this line](https://github.com/redhat-developer/devconsole-operator/pull/174/files#diff-57dae1b5b313e109d7ebdfd77a500c5cR91) is for :)

**Comment by pmacik** [comment]
> Any luck with figuring out how to add secrets to openshift ci?

Haven't tried, yet.

**Pull request merged**
