### PR TITLE
Move operator courier under lint

### PR DESCRIPTION
**Pull request by baijum**
* Change installation of GolangCI-lint tool to use the recommended way.
* This required to run it through CI:
https://jira.coreos.com/browse/ODC-506
* Fix the lint issues produced by `make lint`

### CODE REVIEW

**Comment by sbose78** [comment]
Checking: does this mean that `make test` would not have this, and rather `make lint` would point validate our manifests ?

**Comment by baijum** [comment]
Yes.
I will add it to OpenShift CI.

**Comment by sbose78** [comment]
@baijum  that'll be good!

**Comment by Avni-Sharma** [comment]
> > @baijum that'll be good!
> 
> @sbose78 I have retained the `courier` under `test` target for now. We will remove it once the CI setup for `list` is ready.

@baijum  list ?

**Comment by baijum** [comment]
> > > @baijum that'll be good!
> > 
> > 
> > @sbose78 I have retained the `courier` under `test` target for now. We will remove it once the CI setup for `list` is ready.
> 
> @baijum list ?

I meant `lint`

**Comment by sbose78** [comment]
There are few other changes in this PR as well, hope that was intentional? ;)

**Comment by baijum** [comment]
> There are few other changes in this PR as well, hope that was intentional? ;)

Yes. That is to make Go lint happy.
Should I fix it first in another PR?

**Comment by Avni-Sharma** [comment]
make lint-yaml is not working, lint-go-code is working

**Comment by baijum** [comment]
> make lint-yaml is not working, lint-go-code is working
> subscription_OS3.yaml and subscription_OS4.yaml has extra lines
> actually ending of many files have extra lines. that can be referenced in a different PR?

Yes, let's address those errors in separate PR.

**Comment by baijum** [comment]
@sbose78 @Avni-Sharma Please review it again.

I think we can fix those YAML lint errors separately before OpenShift CI goes live for `lint` target.

**Comment by Avni-Sharma** [comment]
https://github.com/redhat-developer/devconsole-operator/pull/104

**Pull request merged**
