### PR TITLE
Merging pkg/devopsconsole-operator into pkg/devopsconsole

### PR DESCRIPTION
**Pull request by tinakurian**
Should contain a test for gitsource - however there is some test duplication that needs to be sorted out: https://github.com/redhat-developer/devconsole-operator/pull/33/files#r269921383

Will add the gitsource test once the test duplication has been resolved.

### CODE REVIEW

**Comment by sbose78** [comment]
@tinakurian please resolve conflicts.

**Comment by tinakurian** [comment]
> @tinakurian please resolve conflicts.

Done! However, this can't be merged until master is fixed..

**Pull request merged**
